#!/usr/bin/env bash

#
# install-qt-sdk-osx
#
# Copyright (C) 2009-18 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# This archive includes the files required to build against Qt. It
# was created by installing Qt via an interactive installer, and
# manually removing components not needed by RStudio.

QT_VERSION=5.11.1
QT_SDK_BINARY_BASE=qt-unified-mac-x64-3.0.4-online
QT_SDK_BINARY=${QT_SDK_BINARY_BASE}.tar.gz
QT_SDK_INSTALLER=${QT_SDK_BINARY_BASE}.app
QT_SDK_INSTALLER_BIN=${QT_SDK_INSTALLER}/Contents/MacOS/${QT_SDK_BINARY_BASE}
QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
QT_SCRIPT=qt-noninteractive-install-osx.qs 

# set Qt SDK dir if not already defined
if [ -z "$QT_SDK_DIR" ]; then
  QT_SDK_DIR=~/Qt${QT_VERSION}
  QT_SDK_DIR2=~/Qt/Qt${QT_VERSION}
  QT_SDK_DIR3=~/Qt/${QT_VERSION}
fi

if [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
then
   # download and install
   cp ./$QT_SCRIPT /tmp
   curl -L $QT_SDK_URL > /tmp/$QT_SDK_BINARY
   cd /tmp
   tar xzf /tmp/$QT_SDK_BINARY
   
   # online installer sometimes fails, keep trying...
   while [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
   do
      echo "Installing Qt, this will take a while..."
      ./$QT_SDK_INSTALLER_BIN --script /tmp/$QT_SCRIPT
   done
   rm -f /tmp/$QT_SDK_BINARY /tmp/$QT_SCRIPT
   rm -rf /tmp/$QT_SDK_INSTALLER
else
   echo "Qt $QT_VERSION SDK already installed"
fi

