#!/usr/bin/env bash

#
# install-qt-sdk
#
# Copyright (C) 2009-18 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# This archive includes the files required to build against Qt. It
# was created by installing Qt via an interactive installer, and 
# manually removing components not needed by RStudio.

# define QT archive to download
QT_ARCH=x86_64
QT_VERSION=5.11.1
QT_SDK_BINARY=qt-unified-linux-x64-3.0.4-online.run
QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
QT_SCRIPT=qt-noninteractive-install-linux.qs

# set Qt SDK dir if not already defined
if [ -z "$QT_SDK_DIR" ]; then
  QT_SDK_DIR=~/Qt${QT_VERSION}
  QT_SDK_DIR2=~/Qt/Qt${QT_VERSION}
  QT_SDK_DIR3=~/Qt/${QT_VERSION}
fi

if [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
then
   # download and install
   cp ./$QT_SCRIPT /tmp
   wget $QT_SDK_URL -O /tmp/$QT_SDK_BINARY
   chmod u+x /tmp/$QT_SDK_BINARY
   cd /tmp

   # online installer sometimes fails, keep trying...
   while [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
   do
      echo "Installing Qt, this will take a while..."
      ./$QT_SDK_BINARY --script /tmp/$QT_SCRIPT
   done
   rm -f /tmp/$QT_SDK_BINARY /tmp/$QT_SCRIPT
else
   echo "Qt $QT_VERSION SDK already installed"
fi

