#!/usr/bin/env bash

#
# install-qt-sdk
#
# Copyright (C) 2009-18 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# Installs Qt via the online installer at the location in $QT_SDK_DIR.
# If no location provided, checks against a set of common locations and installs
# if not found.

QT_VERSION=5.11.1
QT_SDK_BINARY=qt-unified-linux-x64-3.0.4-online.run
QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
QT_SCRIPT=/tmp/qt-noninteractive-install-linux.qs

# generate script for automatic Qt installation; customizes the install location via $QT_SDK_DIR
function write_qt_script() {
cat << EOF > $QT_SCRIPT

function Controller() {
    installer.autoRejectMessageBoxes();
    installer.installationFinished.connect(function() {
        gui.clickButton(buttons.NextButton);
    })
}

Controller.prototype.WelcomePageCallback = function() {
    gui.clickButton(buttons.NextButton, 3000);
}

Controller.prototype.CredentialsPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.IntroductionPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.TargetDirectoryPageCallback = function()
{
    var widget = gui.currentPageWidget();
    if (widget != null) {
        widget.TargetDirectoryLineEdit.setText("$QT_SDK_DIR");
    }
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.ComponentSelectionPageCallback = function() {
    var widget = gui.currentPageWidget();
     
    widget.selectComponent("qt.qt5.5111.gcc_64");
    widget.selectComponent("qt.qt5.5111.qtwebengine");
    widget.selectComponent("qt.qt5.5111.qtwebengine.gcc_64");
    widget.deselectComponent("qt.qt5.5111.src");
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.LicenseAgreementPageCallback = function() {
    gui.currentPageWidget().AcceptLicenseRadioButton.setChecked(true);
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.StartMenuDirectoryPageCallback = function() {
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.ReadyForInstallationPageCallback = function()
{
    gui.clickButton(buttons.NextButton);
}

Controller.prototype.FinishedPageCallback = function() {
    var checkBoxForm = gui.currentPageWidget().LaunchQtCreatorCheckBoxForm
    if (checkBoxForm && checkBoxForm.launchQtCreatorCheckBox) {
        checkBoxForm.launchQtCreatorCheckBox.checked = false;
    }
    gui.clickButton(buttons.FinishButton);
}
EOF
}

# set Qt SDK dir if not already defined
if [ -z "$QT_SDK_DIR" ]; then

   # Qt install root if path not supplied
   QT_SDK_DIR=~/Qt${QT_VERSION}
   
   # other locations checked for existing installation
   QT_SDK_DIR2=~/Qt/Qt${QT_VERSION}
   QT_SDK_DIR3=~/Qt/${QT_VERSION}
fi

if [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
then
   # If there are Qt account credentials, they break the scripted install. This would happen
   # if user logged into a Qt account during a previous manual install of Qt. We delete the
   # file if it exists.
   rm -f ~/.local/share/Qt/qtaccount.ini

   # download and install
   wget $QT_SDK_URL -O /tmp/$QT_SDK_BINARY
   chmod u+x /tmp/$QT_SDK_BINARY
   write_qt_script

   # online installer sometimes fails, keep trying...
   while [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
   do
      echo "Installing Qt, this will take a while."
      echo " - Ignore warnings about QtAccount credentials."
      echo " - Do not click on the setup interface, it is controlled by a script."
      /tmp/$QT_SDK_BINARY --script $QT_SCRIPT
   done
   rm -f /tmp/$QT_SDK_BINARY $QT_SCRIPT
else
   echo "Qt $QT_VERSION SDK already installed"
fi

